Repository NationalSecurityAgency/ghidra, pull requests merged in 2022-05, with the labels that each got.

#4211 Minor typos/grammar in totd/tips.txt
  Ghidra/Features/Base/src/main/resources/ghidra/app/plugin/core/totd/tips.txt
Labels: Type: Spelling/Typo

#4196 Use ComSpec in Manual Viewer
  Ghidra/Features/Base/src/main/java/ghidra/util/ManualViewerCommandWrappedOption.java
Labels: Type: Security

#4003 fix #4002 - fix a typo in RISC-V pattern constraints filename
  Ghidra/Processors/RISCV/data/patterns/patternconstraints.xml
Labels: Feature: Processor/RISC-V, Status: Internal
