Repository NationalSecurityAgency/ghidra, pull requests merged in 2022-11, with the labels that each got.

#4699 Python Interpreter: Allow code completion to be started from anywhere in the input string
  Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/interpreter/InterpreterConnection.java
  Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/interpreter/InterpreterPanel.java
  Ghidra/Features/Base/src/test.slow/java/ghidra/app/plugin/core/interpreter/InterpreterPanelTest.java
  Ghidra/Features/Python/python-src/jintrospect.py
  Ghidra/Features/Python/src/main/java/ghidra/python/GhidraPythonInterpreter.java
  Ghidra/Features/Python/src/main/java/ghidra/python/PythonPlugin.java
  Ghidra/Features/Python/src/test.slow/java/ghidra/python/PythonCodeCompletionTest.java
Labels: Feature: Python, Status: Internal

#4743 Update Module.manifest after upgrading protobuf to 3.21.8
  Ghidra/Debug/Debugger-gadp/Module.manifest
Labels: Feature: Build, Status: Internal

#4734 Fix icmpapi.h parsing error in example GDT script
  Ghidra/Features/Base/ghidra_scripts/CreateExampleGDTArchiveScript.java
Labels: Status: Internal

#3808 3807: fix DLGTEMPLATEEX parsing
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/DialogResourceDataType.java
  Ghidra/Framework/SoftwareModeling/src/test/java/ghidra/program/model/data/DialogResourceDataTypeTest.java
Labels: Feature: Loader/PE, Status: Internal

#4757 Removed unnecessary Javadoc option
  gradle/root/distribution.gradle
Labels: Feature: Build, Status: Internal

#4762 Fix 64 bits Ext4 inode table offset calculation.
  Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/ext4/Ext4Analyzer.java
  Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/ext4/NewExt4Analyzer.java
Labels: Feature: Filesystem, Status: Internal
