Repository NationalSecurityAgency/ghidra, pull requests merged in 2022-02, with the labels that each got.

#3791 Resolve TODO: delete unused class
  Ghidra/Framework/Graph/src/main/java/ghidra/graph/viewer/edge/InitializeCircuitsRunnable.java
Labels: Feature: Graphing

#3824 Fix typo and formatting in DecompileOptions
  Ghidra/Features/Decompiler/src/main/java/ghidra/app/decompiler/DecompileOptions.java
Labels: Type: Spelling/Typo

#3844 Remove workaround for old Gradle version we don't support anymore
  gradle/javaProject.gradle
Labels: Feature: Build

#3963 SQUOTE bug fix in the shell
  Ghidra/Debug/Framework-Debugging/src/main/java/ghidra/dbg/util/ShellUtils.java
Labels: Feature: Debugger

#3764 Fixed toCamel so that only _ are converted to uppercase letters
  Ghidra/Features/PDB/src/main/java/ghidra/app/util/bin/format/pdb/PdbKind.java
Labels: Feature: PDB

#3964 Bug fix for creating symbol
  Ghidra/Features/PDB/src/main/java/ghidra/app/util/pdb/pdbapplicator/LabelSymbolApplier.java
Labels: Feature: PDB
