Repository NationalSecurityAgency/ghidra, pull requests merged in 2022-07, with the labels that each got.

#4239 Don't skip the first pcodetest artifact if target directory does not exist.
  Ghidra/Extensions/SleighDevTools/pcodetest/build.py
Labels: Feature: Testing, Status: Internal

#3156 Fix locale issue in MacintoshTimeStampDataType
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/MacintoshTimeStampDataType.java
Labels: Feature: Loader/Mach-O, Status: Internal

#4307 Port pcodetest builder to Python 3.
  Ghidra/Extensions/SleighDevTools/pcodetest/build
  Ghidra/Extensions/SleighDevTools/pcodetest/build.py
  Ghidra/Extensions/SleighDevTools/pcodetest/pcodetest.py
Labels: Feature: Testing, Feature: Processor, Status: Internal

#4181 add noreturn functions in Windows WDK
  Ghidra/Features/Base/data/PEFunctionsThatDoNotReturn
Labels: Feature: Analysis, Feature: Loader/PE

#4249 6502: Fix PLP opcode.
  Ghidra/Processors/6502/data/languages/6502.slaspec
Labels: Feature: Processor/6502, Status: Internal

#2590 RISCV Bad long size (and alignment)
  Ghidra/Processors/RISCV/data/languages/riscv64-fp.cspec
  Ghidra/Processors/RISCV/data/languages/riscv64.cspec
Labels: Feature: Processor/RISC-V, Status: Internal

#4344 Sleigh x86 improvements
  Ghidra/Processors/x86/data/languages/ia.sinc
Labels: Feature: Processor/x86, Status: Internal
