Repository NationalSecurityAgency/ghidra, pull requests merged in 2022-06, with the labels that each got.

#4286 Make it possible to import symbols into arbitrary memory regions
  Ghidra/Features/Python/ghidra_scripts/ImportSymbolsScript.py
Labels: Feature: Scripting, Status: Internal

#4299 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Status: Internal

#3222 Add vfma/vfnma/vfms/vfnms to arm
  Ghidra/Processors/ARM/data/languages/ARM7_be.slaspec
  Ghidra/Processors/ARM/data/languages/ARM7_le.slaspec
  Ghidra/Processors/ARM/data/languages/ARM8_be.slaspec
  Ghidra/Processors/ARM/data/languages/ARM8_le.slaspec
  Ghidra/Processors/ARM/data/languages/ARMneon.sinc
Labels: Feature: Processor/ARM, Status: Internal

#4354 Fixed comments for OperandType flags
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/lang/OperandType.java
Labels: Type: Spelling/Typo

#4368 Fix typo
  Ghidra/Features/PDB/src/main/java/ghidra/app/plugin/core/analysis/PdbAnalyzer.java
Labels: Type: Spelling/Typo

#4161 Fix NullPointerException which occurs when getAddressValue returns null
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/TLSDataDirectory.java
Labels: Feature: Loader/PE

#3787 Fix FunctionStartAnalyzer's control flow
  Ghidra/Features/BytePatterns/src/main/java/ghidra/app/analyzers/FunctionStartAnalyzer.java
Labels: Feature: Analysis

#4381 Fixed typos in Pointer DataType description commments
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer24DataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer32DataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer40DataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer48DataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer56DataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer64DataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Pointer8DataType.java
Labels: Type: Spelling/Typo
