Repository NationalSecurityAgency/ghidra, pull requests merged in 2023-06, with the labels that each got.

#5178 Fix a few issues with PEF relocation and loading
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pef/LoaderRelocationHeader.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pef/RelocLgRepeat.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pef/RelocLgSetOrBySection.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pef/RelocSmRepeat.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pef/Relocation.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pef/SectionHeader.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/PefLoader.java
Labels: Status: Internal, Feature: Loader/PEF

#5395 Close FileDataTypeManager in CompareGDTs.java
  Ghidra/Features/Base/ghidra_scripts/CompareGDTs.java
Labels: Status: Internal

#5409 Check for negative length in `SemisparseByteArray.putData()`
  Ghidra/Framework/Emulation/src/main/java/ghidra/generic/util/datastruct/SemisparseByteArray.java
Labels: Status: Internal

#5437 bugfix: pythonRun.bat ignored its arguments
  Ghidra/RuntimeScripts/Windows/support/pythonRun.bat
Labels: Feature: Launch, Status: Internal

#5464 Fix two typos
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/PcodeOp.java
  GhidraDocs/languages/html/sleigh_constructors.html
Labels: Type: Spelling/Typo

#5492 Prefer getComponentContaining over getComponentAt where applicible
  Ghidra/Features/Base/src/main/java/ghidra/app/cmd/data/CreateDataInStructureBackgroundCmd.java
  Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/analysis/ObjectiveC1_MessageAnalyzer.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/ResourceDataDirectory.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/viewer/listingpanel/ProgramBigListingModel.java
  Ghidra/Features/Base/src/test.slow/java/ghidra/app/plugin/core/codebrowser/ExpandCollapseDataActionsTest.java
Labels: Status: Internal

#3777 Fix display error in which checkout progress displayed starts from 0 instead of 1
  Ghidra/Framework/Project/src/main/java/ghidra/framework/main/projectdata/actions/VersionControlCheckOutAction.java
Labels: Status: Internal
