Repository NationalSecurityAgency/ghidra, pull requests merged in 2023-11, with the labels that each got.

#5315 Fix call_frame_cfa value for ppc
  Ghidra/Processors/PowerPC/data/languages/ppc.dwarf
Labels: Feature: Processor/PowerPC, Feature: DWARF, Status: Internal

#5954 fix typo 'Popluate' on FidDb Populate Results Window
  Ghidra/Features/FunctionID/src/main/java/ghidra/feature/fid/service/DefaultFidPopulateResultReporter.java
Labels: Type: Spelling/Typo, Status: Internal

#5958 Adding missing ids from ddraw.h and d3d.h
  Ghidra/Features/Base/data/typeinfo/win32/msvcrt/iids.txt
Labels: Status: Internal

#5978 ghidra: fixed paths with spaces unable to be imported into ghidra
  Ghidra/Features/Base/src/main/java/ghidra/framework/main/datatree/LinuxFileUrlHandler.java
Labels: Status: Internal
