Repository NationalSecurityAgency/ghidra, pull requests merged in 2024-10, with the labels that each got.

#6978 missing word "address" in Sleigh docs
  GhidraDocs/languages/html/sleigh_definitions.html
Labels: Type: Spelling/Typo, Status: Internal

#6998 typos etc in GhidraFilesystemStorage.html
  GhidraDocs/GhidraFilesystemStorage.html
Labels: Type: Spelling/Typo, Status: Internal

#6979 GhidraSleighEditor docs stated wrong directory for `build_README.txt`
  GhidraBuild/EclipsePlugins/GhidraSleighEditor/ghidra.xtext.sleigh/GhidraSleighEditor_README.html
  GhidraDocs/languages/html/sleigh_definitions.html
  GhidraDocs/languages/html/sleigh_symbols.html
Labels: Feature: Documentation, Status: Internal

#7008 minor English copyedit
  GhidraDocs/languages/html/pcoderef.html
Labels: Type: Spelling/Typo, Status: Internal

#7023 Update VSCodeProjectScript.java to pre-populate formatter settings
  Ghidra/Features/Base/ghidra_scripts/VSCodeProjectScript.java
Labels: Feature: Scripting, Status: Internal

#7059 Base: Fix typo in AskScript.properties
  Ghidra/Features/Base/ghidra_scripts/AskScript.properties
Labels: Feature: Scripting, Status: Internal

#7076 BSim: Fix paths in DatabaseConfiguration.html
  Ghidra/Features/BSim/src/main/help/help/topics/BSim/DatabaseConfiguration.html
Labels: Feature: Documentation, Type: Spelling/Typo, Status: Internal

#7080 English copyedit
  GhidraDocs/languages/html/sleigh_constructors.html
Labels: Type: Spelling/Typo, Status: Internal

#7090 + macOS macho-o dynamic lib file extension .dylib to file dialog filter
  Ghidra/Features/Base/src/main/java/ghidra/plugin/importer/ImporterUtilities.java
Labels: Status: Internal

#7070 Let FileSystem extensions set filetype icons in filesystem browser
  Ghidra/Features/Base/src/main/java/ghidra/formats/gfilesystem/fileinfo/FileAttributeType.java
  Ghidra/Features/Base/src/main/java/ghidra/plugins/fsbrowser/FSBComponentProvider.java
  Ghidra/Features/Base/src/main/java/ghidra/plugins/fsbrowser/FSBFileNode.java
Labels: Feature: Filesystem, Status: Internal

#7086 add oxygen icons for .exe / .dll / .dylib plus a few others
  Ghidra/Features/Base/data/base.file.extensions.icons.theme.properties
Labels: Feature: GUI, Feature: Filesystem, Status: Internal

#7112 spelling of 'descendant' in identifiers, error messages, and comments
  Ghidra/Debug/Debugger/src/main/java/ghidra/app/plugin/core/debug/gui/objects/components/ObjectTree.java
  Ghidra/Debug/Debugger/src/main/java/ghidra/app/plugin/core/debug/gui/stack/vars/VariableValueUtils.java
  Ghidra/Features/Decompiler/ghidra_scripts/classrecovery/RTTIClassRecoverer.java
  Ghidra/Features/Decompiler/ghidra_scripts/classrecovery/RTTIWindowsClassRecoverer.java
  Ghidra/Features/Decompiler/ghidra_scripts/classrecovery/RecoveredClassHelper.java
  Ghidra/Features/Decompiler/src/decompile/cpp/ruleaction.cc
  Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc
  Ghidra/Features/GhidraServer/src/main/java/ghidra/server/store/RepositoryFolder.java
  Ghidra/Framework/Docking/src/main/java/docking/DockingUtils.java
  Ghidra/Framework/Docking/src/main/java/docking/widgets/tree/CoreGTreeNode.java
  Ghidra/Framework/FileSystem/src/main/java/ghidra/framework/store/FileSystem.java
  Ghidra/Framework/Project/src/main/java/ghidra/framework/main/projectdata/actions/ProjectDataPasteAction.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/DecisionNode.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/database/module/ModuleManager.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/symbol/Namespace.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/util/GroupPath.java
Labels: Type: Spelling/Typo, Status: Internal

#7014 FunctionID: Add scripts for creating and attaching FID databases
  Ghidra/Features/FunctionID/ghidra_scripts/AttachFidDatabase.java
  Ghidra/Features/FunctionID/ghidra_scripts/CreateEmptyFidDatabase.java
Labels: Feature: Scripting, Feature: FID, Status: Internal
