Repository NationalSecurityAgency/ghidra, pull requests merged in 2024-09, with the labels that each got.

#6841 Fix null exception in PropagateExternalParametersScript.java
  Ghidra/Features/Base/ghidra_scripts/PropagateExternalParametersScript.java
Labels: Status: Internal

#6881 Fix spelling error in example code in Application.java
  Ghidra/Framework/Generic/src/main/java/ghidra/framework/Application.java
Labels: Type: Spelling/Typo, Status: Internal

#6885 Fix typo ghidra words on comments
  Ghidra/Features/Base/src/main/java/ghidra/test/TestEnv.java
  Ghidra/Framework/Docking/src/main/java/docking/test/AbstractDockingTest.java
Labels: Type: Spelling/Typo, Status: Internal

#6823 Fix wrong namespaces when using XML imports
  Ghidra/Features/Base/src/main/java/ghidra/app/util/xml/SymbolTableXmlMgr.java
Labels: Feature: Loader/XML, Status: Internal

#6916 Fix Spelling Mistakes
  Ghidra/Framework/Gui/src/test/java/generic/theme/FontModifierTest.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode/LinkedByteBuffer.java
Labels: Type: Spelling/Typo, Status: Internal
