Repository NationalSecurityAgency/ghidra, pull requests merged in 2024-01, with the labels that each got.

#5989 Adding IIDs from Windows SDK 10.0.22621.0.
  Ghidra/Features/Base/data/typeinfo/win32/msvcrt/iids.txt
Labels: Status: Internal

#6076 fix keybinding javadoc reference
  Ghidra/Framework/Docking/src/main/java/docking/KeyBindingPrecedence.java
Labels: Feature: Documentation, Status: Internal

#5965 Add support for PowerPC COFF Relocations
  Ghidra/Processors/PowerPC/src/main/java/ghidra/app/util/bin/format/coff/relocation/PowerPC_CoffRelocationHandler.java
Labels: Feature: Processor/PowerPC, Feature: Loader/COFF, Status: Internal

#6092 Adding missing DirectX 7 IIDs.
  Ghidra/Features/Base/data/typeinfo/win32/msvcrt/iids.txt
Labels: Status: Internal

#6121 Fix typo in GTree.java "Exapnd" -> "Expand"
  Ghidra/Framework/Docking/src/main/java/docking/widgets/tree/GTree.java
Labels: Type: Spelling/Typo, Status: Internal

#6140 Remove extra check Extensions.java
  Ghidra/Framework/Generic/src/main/java/ghidra/util/extensions/Extensions.java
Labels: Feature: Extensions, Status: Internal

#6145 Fix ARM64E_KERNEL chained pointer handling in Mach-O binaries (Issue #6144).
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/macho/dyld/DyldChainedPtr.java
Labels: Feature: Loader/Mach-O, Status: Internal
