Repository NationalSecurityAgency/ghidra, pull requests merged in 2024-03, with the labels that each got.

#6302 Fix Mach-O import when no segment contains the header
  Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/MachoProgramBuilder.java
Labels: Feature: Loader/Mach-O, Status: Internal

#6331 Add support for FreeBSD ARM 64bit (no debugger support)
  GPL/DemanglerGnu/build.gradle
  GPL/nativeBuildProperties.gradle
  GPL/nativePlatforms.gradle
  Ghidra/Features/Decompiler/buildNatives.gradle
  Ghidra/Framework/Generic/src/main/java/ghidra/framework/Platform.java
  GhidraDocs/InstallationGuide.html
Labels: Status: Internal

#6345 Fix 132 typos
  Ghidra/Configurations/Public_Release/src/global/docs/ChangeHistory.html
  Ghidra/Extensions/SleighDevTools/pcodetest/c_src/pcode_test.h
  Ghidra/Features/Base/src/main/help/help/topics/DataTypeEditors/StructureEditor.htm
  Ghidra/Features/Base/src/main/help/help/topics/ImporterPlugin/importer.htm
  Ghidra/Features/Base/src/main/help/help/topics/Tables/GhidraTableHeaders.html
  Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/searchmem/MemSearchDialog.java
  Ghidra/Features/Base/src/main/java/ghidra/app/plugin/core/searchmem/MemSearchPlugin.java
  Ghidra/Features/Base/src/main/java/ghidra/app/plugin/debug/GenerateOldLanguagePlugin.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/elf/ElfHeader.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/opinion/XmlLoader.java
  Ghidra/Features/Base/src/main/java/ghidra/app/util/xml/ProgramInfo.java
  Ghidra/Features/Base/src/main/java/ghidra/test/ToyProgramBuilder.java
  Ghidra/Features/Base/src/main/java/ghidra/test/processors/support/PCodeTestControlBlock.java
  Ghidra/Features/Base/src/main/java/ghidra/util/state/ContextState.java
  Ghidra/Features/Base/src/main/java/ghidra/util/table/field/BytesTableColumn.java
  Ghidra/Features/Base/src/main/java/ghidra/util/table/projectdata/column/EndianProjectDataColumn.java
  Ghidra/Features/Base/src/test.slow/java/ghidra/app/plugin/core/searchmem/AbstractMemSearchTest.java
  Ghidra/Features/Base/src/test.slow/java/ghidra/app/plugin/core/searchmem/MemSearchAsciiTest.java
  Ghidra/Features/Base/src/test/java/ghidra/program/model/data/CompositeZeroArrayTest.java
  Ghidra/Features/Base/src/test/java/ghidra/program/model/data/StructureDataTypeTest.java
  Ghidra/Features/Decompiler/src/decompile/cpp/cast.hh
  Ghidra/Features/Decompiler/src/decompile/cpp/emulateutil.hh
  Ghidra/Features/Decompiler/src/decompile/cpp/sleigh_arch.hh
  Ghidra/Features/Decompiler/src/decompile/cpp/slgh_compile.cc
  Ghidra/Features/Decompiler/src/main/doc/decompileplugin.xml
  Ghidra/Features/Decompiler/src/main/doc/pcoderef.xml
  Ghidra/Features/Decompiler/src/main/doc/sleigh.xml
  Ghidra/Features/Decompiler/src/main/help/help/topics/DecompilePlugin/DecompilerConcepts.html
  Ghidra/Features/Sarif/src/main/java/sarif/SarifLoader.java
  Ghidra/Features/Sarif/src/main/java/sarif/managers/ProgramInfo.java
  Ghidra/Framework/Emulation/src/main/java/ghidra/pcode/memstate/MemoryBank.java
  Ghidra/Framework/Generic/src/main/java/ghidra/util/DataConverter.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/app/plugin/processors/sleigh/SleighDebugLogger.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/pcodeCPort/slgh_compile/SleighCompile.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/database/mem/MemoryMapDB.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/DataOrganizationImpl.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/EndianSettingsDefinition.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/StringDataInstance.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Structure.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/StructureDataType.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/data/Union.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/lang/Endian.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/lang/LanguageService.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/lang/SleighLanguageDescription.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/listing/VariableStorage.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/mem/MemBuffer.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/util/AddressEvaluator.java
  Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/util/DefaultLanguageService.java
  Ghidra/Framework/SoftwareModeling/src/test/java/ghidra/program/database/data/StructureDBTest.java
  Ghidra/Framework/SoftwareModeling/src/test/java/ghidra/program/database/data/UnionDBTest.java
  Ghidra/Processors/ARM/data/languages/ARMinstructions.sinc
  Ghidra/Processors/Toy/data/languages/old/v01stuff/toy.sinc
  Ghidra/Processors/Xtensa/data/languages/xtensa.cspec
  GhidraDocs/languages/html/pcodedescription.html
  GhidraDocs/languages/html/pcoderef.html
  GhidraDocs/languages/html/sleigh.html
  GhidraDocs/languages/html/sleigh_definitions.html
  GhidraDocs/languages/html/sleigh_tokens.html
Labels: Type: Spelling/Typo, Status: Internal
