Repository NationalSecurityAgency/ghidra, pull requests merged in 2024-06, with the labels that each got.

#6540 Decompiler: Fix inputs sometimes being swapped for operations `FLOAT_LESS` and `FLOAT_LESSEQUAL` in rule `subflow_convert`
  Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc
Labels: Feature: Decompiler, Status: Internal

#6637 Update InstallationGuide.html to remove instructions for Windows 7
  GhidraDocs/InstallationGuide.html
Labels: Feature: Documentation, Status: Internal

#6657 Fix initialization of OBJECT_HASHCODE in PrivatelyQueuedListener
  Ghidra/Debug/ProposedUtils/src/main/java/ghidra/util/datastruct/PrivatelyQueuedListener.java
Labels: Feature: Build, Feature: Debugger, Status: Internal
